# Absolute path to the go-emacs Package directory. This should be set automatically
# by go-emacs.el if that function is used to publish the blog. It can also be set
# with with passing it with the -b flag when using the go-emacs binary.
goEmacsPackageDir=""

# Absolute path to output directory. Defaults to ~/Documents/go-emacs/static
output=""

# The name should be filled in, but the others can be left blank to remove
[contact]
name = "Joe Dev"
email = "joe@oregon.io"
git = "https://github.com/joedev"
linkedin = "https://www.linkedin.com/in/joe-dev-123456/"

[pages]
#Absolute path to pages directory. Defaults to ~/Documents/go-emacs/pages
dir = ""

[posts]
#Absolute path to post directory. Defaults to ~/Documents/go-emacs/posts
dir = ""

[resume]
# Set to true to include a resume page with a "download pdf" link.
isResume=true
#Absolute path to resume directory. Defaults to ~/Documents/go-emacs/resume
dir=""
# Leave blank for no resume pdf, add the filename of the resume found in the resume folder
pdf=""

[site]
# This will be the meta tag for the website.
meta = "A developer blog sharing insights on full-stack web development, API design, cloud infrastructure, and modern programming languages."
# This will be the title for the Nav and the <title> for the home page.
title = "Joe Dev Zone"
#Sub header on the home page. Leave blank to remove
subheader="Web development - Stuff - DevOps"
#Set to true for card with thumbnail style, false for a list style
cards=true
#This can be any string and will appear below the sub header. Leave blank to remove
skilltags="Haskell | C# | Angular | Docker | MongoDB | AWS | VScode"
# Set to false to skip generation of rss
rss=true
# Site public URL. Used for Rss. If rss=false, no need to set this.
url="https://joe-dev.com/"
